post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "benefits of fullstack open",
    "author": "Antti Salo",
    "url": "blogger.com/fullstack",
    "likes": 3,
    "userId": "677d1463dead9881d9f23fa5"
}