post http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "I Love Winter",
    "author": "Ma Lu",
    "url": "blogger.com/blogger_winter2025",
    "likes": 3,
    "userId": "677bec5831a2307b758d4f85"
}